version: '3.8'

services:
  gym-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-app
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=gym-db;Database=GymDb;User Id=sa;Password=GymStrongPass123!;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "5002:8080"
    depends_on:
      - gym-db

  gym-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gym-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=GymStrongPass123!
    volumes:
      - gym-db-data:/var/opt/mssql

volumes:
  gym-db-data:
